# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jermiel/Documents/Structure_donnees_avance/projet/galaxy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jermiel/Documents/Structure_donnees_avance/projet/galaxy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jermiel/Documents/Structure_donnees_avance/projet/galaxy/CMakeFiles /home/jermiel/Documents/Structure_donnees_avance/projet/galaxy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jermiel/Documents/Structure_donnees_avance/projet/galaxy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my-private-galaxy

# Build rule for target.
my-private-galaxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my-private-galaxy
.PHONY : my-private-galaxy

# fast build rule for target.
my-private-galaxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/build
.PHONY : my-private-galaxy/fast

3D/src/Boite.o: 3D/src/Boite.cpp.o
.PHONY : 3D/src/Boite.o

# target to build an object file
3D/src/Boite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Boite.cpp.o
.PHONY : 3D/src/Boite.cpp.o

3D/src/Boite.i: 3D/src/Boite.cpp.i
.PHONY : 3D/src/Boite.i

# target to preprocess a source file
3D/src/Boite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Boite.cpp.i
.PHONY : 3D/src/Boite.cpp.i

3D/src/Boite.s: 3D/src/Boite.cpp.s
.PHONY : 3D/src/Boite.s

# target to generate assembly for a file
3D/src/Boite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Boite.cpp.s
.PHONY : 3D/src/Boite.cpp.s

3D/src/IIntegrator.o: 3D/src/IIntegrator.cpp.o
.PHONY : 3D/src/IIntegrator.o

# target to build an object file
3D/src/IIntegrator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IIntegrator.cpp.o
.PHONY : 3D/src/IIntegrator.cpp.o

3D/src/IIntegrator.i: 3D/src/IIntegrator.cpp.i
.PHONY : 3D/src/IIntegrator.i

# target to preprocess a source file
3D/src/IIntegrator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IIntegrator.cpp.i
.PHONY : 3D/src/IIntegrator.cpp.i

3D/src/IIntegrator.s: 3D/src/IIntegrator.cpp.s
.PHONY : 3D/src/IIntegrator.s

# target to generate assembly for a file
3D/src/IIntegrator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IIntegrator.cpp.s
.PHONY : 3D/src/IIntegrator.cpp.s

3D/src/IntegratorADB5.o: 3D/src/IntegratorADB5.cpp.o
.PHONY : 3D/src/IntegratorADB5.o

# target to build an object file
3D/src/IntegratorADB5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorADB5.cpp.o
.PHONY : 3D/src/IntegratorADB5.cpp.o

3D/src/IntegratorADB5.i: 3D/src/IntegratorADB5.cpp.i
.PHONY : 3D/src/IntegratorADB5.i

# target to preprocess a source file
3D/src/IntegratorADB5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorADB5.cpp.i
.PHONY : 3D/src/IntegratorADB5.cpp.i

3D/src/IntegratorADB5.s: 3D/src/IntegratorADB5.cpp.s
.PHONY : 3D/src/IntegratorADB5.s

# target to generate assembly for a file
3D/src/IntegratorADB5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorADB5.cpp.s
.PHONY : 3D/src/IntegratorADB5.cpp.s

3D/src/IntegratorADB6.o: 3D/src/IntegratorADB6.cpp.o
.PHONY : 3D/src/IntegratorADB6.o

# target to build an object file
3D/src/IntegratorADB6.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorADB6.cpp.o
.PHONY : 3D/src/IntegratorADB6.cpp.o

3D/src/IntegratorADB6.i: 3D/src/IntegratorADB6.cpp.i
.PHONY : 3D/src/IntegratorADB6.i

# target to preprocess a source file
3D/src/IntegratorADB6.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorADB6.cpp.i
.PHONY : 3D/src/IntegratorADB6.cpp.i

3D/src/IntegratorADB6.s: 3D/src/IntegratorADB6.cpp.s
.PHONY : 3D/src/IntegratorADB6.s

# target to generate assembly for a file
3D/src/IntegratorADB6.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorADB6.cpp.s
.PHONY : 3D/src/IntegratorADB6.cpp.s

3D/src/IntegratorRK4.o: 3D/src/IntegratorRK4.cpp.o
.PHONY : 3D/src/IntegratorRK4.o

# target to build an object file
3D/src/IntegratorRK4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRK4.cpp.o
.PHONY : 3D/src/IntegratorRK4.cpp.o

3D/src/IntegratorRK4.i: 3D/src/IntegratorRK4.cpp.i
.PHONY : 3D/src/IntegratorRK4.i

# target to preprocess a source file
3D/src/IntegratorRK4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRK4.cpp.i
.PHONY : 3D/src/IntegratorRK4.cpp.i

3D/src/IntegratorRK4.s: 3D/src/IntegratorRK4.cpp.s
.PHONY : 3D/src/IntegratorRK4.s

# target to generate assembly for a file
3D/src/IntegratorRK4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRK4.cpp.s
.PHONY : 3D/src/IntegratorRK4.cpp.s

3D/src/IntegratorRK5.o: 3D/src/IntegratorRK5.cpp.o
.PHONY : 3D/src/IntegratorRK5.o

# target to build an object file
3D/src/IntegratorRK5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRK5.cpp.o
.PHONY : 3D/src/IntegratorRK5.cpp.o

3D/src/IntegratorRK5.i: 3D/src/IntegratorRK5.cpp.i
.PHONY : 3D/src/IntegratorRK5.i

# target to preprocess a source file
3D/src/IntegratorRK5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRK5.cpp.i
.PHONY : 3D/src/IntegratorRK5.cpp.i

3D/src/IntegratorRK5.s: 3D/src/IntegratorRK5.cpp.s
.PHONY : 3D/src/IntegratorRK5.s

# target to generate assembly for a file
3D/src/IntegratorRK5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRK5.cpp.s
.PHONY : 3D/src/IntegratorRK5.cpp.s

3D/src/IntegratorRKF4.o: 3D/src/IntegratorRKF4.cpp.o
.PHONY : 3D/src/IntegratorRKF4.o

# target to build an object file
3D/src/IntegratorRKF4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRKF4.cpp.o
.PHONY : 3D/src/IntegratorRKF4.cpp.o

3D/src/IntegratorRKF4.i: 3D/src/IntegratorRKF4.cpp.i
.PHONY : 3D/src/IntegratorRKF4.i

# target to preprocess a source file
3D/src/IntegratorRKF4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRKF4.cpp.i
.PHONY : 3D/src/IntegratorRKF4.cpp.i

3D/src/IntegratorRKF4.s: 3D/src/IntegratorRKF4.cpp.s
.PHONY : 3D/src/IntegratorRKF4.s

# target to generate assembly for a file
3D/src/IntegratorRKF4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/IntegratorRKF4.cpp.s
.PHONY : 3D/src/IntegratorRKF4.cpp.s

3D/src/ModelNBody.o: 3D/src/ModelNBody.cpp.o
.PHONY : 3D/src/ModelNBody.o

# target to build an object file
3D/src/ModelNBody.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/ModelNBody.cpp.o
.PHONY : 3D/src/ModelNBody.cpp.o

3D/src/ModelNBody.i: 3D/src/ModelNBody.cpp.i
.PHONY : 3D/src/ModelNBody.i

# target to preprocess a source file
3D/src/ModelNBody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/ModelNBody.cpp.i
.PHONY : 3D/src/ModelNBody.cpp.i

3D/src/ModelNBody.s: 3D/src/ModelNBody.cpp.s
.PHONY : 3D/src/ModelNBody.s

# target to generate assembly for a file
3D/src/ModelNBody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/ModelNBody.cpp.s
.PHONY : 3D/src/ModelNBody.cpp.s

3D/src/NBodyWnd.o: 3D/src/NBodyWnd.cpp.o
.PHONY : 3D/src/NBodyWnd.o

# target to build an object file
3D/src/NBodyWnd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/NBodyWnd.cpp.o
.PHONY : 3D/src/NBodyWnd.cpp.o

3D/src/NBodyWnd.i: 3D/src/NBodyWnd.cpp.i
.PHONY : 3D/src/NBodyWnd.i

# target to preprocess a source file
3D/src/NBodyWnd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/NBodyWnd.cpp.i
.PHONY : 3D/src/NBodyWnd.cpp.i

3D/src/NBodyWnd.s: 3D/src/NBodyWnd.cpp.s
.PHONY : 3D/src/NBodyWnd.s

# target to generate assembly for a file
3D/src/NBodyWnd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/NBodyWnd.cpp.s
.PHONY : 3D/src/NBodyWnd.cpp.s

3D/src/Octree.o: 3D/src/Octree.cpp.o
.PHONY : 3D/src/Octree.o

# target to build an object file
3D/src/Octree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Octree.cpp.o
.PHONY : 3D/src/Octree.cpp.o

3D/src/Octree.i: 3D/src/Octree.cpp.i
.PHONY : 3D/src/Octree.i

# target to preprocess a source file
3D/src/Octree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Octree.cpp.i
.PHONY : 3D/src/Octree.cpp.i

3D/src/Octree.s: 3D/src/Octree.cpp.s
.PHONY : 3D/src/Octree.s

# target to generate assembly for a file
3D/src/Octree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Octree.cpp.s
.PHONY : 3D/src/Octree.cpp.s

3D/src/Particule3D.o: 3D/src/Particule3D.cpp.o
.PHONY : 3D/src/Particule3D.o

# target to build an object file
3D/src/Particule3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Particule3D.cpp.o
.PHONY : 3D/src/Particule3D.cpp.o

3D/src/Particule3D.i: 3D/src/Particule3D.cpp.i
.PHONY : 3D/src/Particule3D.i

# target to preprocess a source file
3D/src/Particule3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Particule3D.cpp.i
.PHONY : 3D/src/Particule3D.cpp.i

3D/src/Particule3D.s: 3D/src/Particule3D.cpp.s
.PHONY : 3D/src/Particule3D.s

# target to generate assembly for a file
3D/src/Particule3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/Particule3D.cpp.s
.PHONY : 3D/src/Particule3D.cpp.s

3D/src/SDLWnd.o: 3D/src/SDLWnd.cpp.o
.PHONY : 3D/src/SDLWnd.o

# target to build an object file
3D/src/SDLWnd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/SDLWnd.cpp.o
.PHONY : 3D/src/SDLWnd.cpp.o

3D/src/SDLWnd.i: 3D/src/SDLWnd.cpp.i
.PHONY : 3D/src/SDLWnd.i

# target to preprocess a source file
3D/src/SDLWnd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/SDLWnd.cpp.i
.PHONY : 3D/src/SDLWnd.cpp.i

3D/src/SDLWnd.s: 3D/src/SDLWnd.cpp.s
.PHONY : 3D/src/SDLWnd.s

# target to generate assembly for a file
3D/src/SDLWnd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/SDLWnd.cpp.s
.PHONY : 3D/src/SDLWnd.cpp.s

3D/src/main.o: 3D/src/main.cpp.o
.PHONY : 3D/src/main.o

# target to build an object file
3D/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/main.cpp.o
.PHONY : 3D/src/main.cpp.o

3D/src/main.i: 3D/src/main.cpp.i
.PHONY : 3D/src/main.i

# target to preprocess a source file
3D/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/main.cpp.i
.PHONY : 3D/src/main.cpp.i

3D/src/main.s: 3D/src/main.cpp.s
.PHONY : 3D/src/main.s

# target to generate assembly for a file
3D/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-private-galaxy.dir/build.make CMakeFiles/my-private-galaxy.dir/3D/src/main.cpp.s
.PHONY : 3D/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my-private-galaxy"
	@echo "... 3D/src/Boite.o"
	@echo "... 3D/src/Boite.i"
	@echo "... 3D/src/Boite.s"
	@echo "... 3D/src/IIntegrator.o"
	@echo "... 3D/src/IIntegrator.i"
	@echo "... 3D/src/IIntegrator.s"
	@echo "... 3D/src/IntegratorADB5.o"
	@echo "... 3D/src/IntegratorADB5.i"
	@echo "... 3D/src/IntegratorADB5.s"
	@echo "... 3D/src/IntegratorADB6.o"
	@echo "... 3D/src/IntegratorADB6.i"
	@echo "... 3D/src/IntegratorADB6.s"
	@echo "... 3D/src/IntegratorRK4.o"
	@echo "... 3D/src/IntegratorRK4.i"
	@echo "... 3D/src/IntegratorRK4.s"
	@echo "... 3D/src/IntegratorRK5.o"
	@echo "... 3D/src/IntegratorRK5.i"
	@echo "... 3D/src/IntegratorRK5.s"
	@echo "... 3D/src/IntegratorRKF4.o"
	@echo "... 3D/src/IntegratorRKF4.i"
	@echo "... 3D/src/IntegratorRKF4.s"
	@echo "... 3D/src/ModelNBody.o"
	@echo "... 3D/src/ModelNBody.i"
	@echo "... 3D/src/ModelNBody.s"
	@echo "... 3D/src/NBodyWnd.o"
	@echo "... 3D/src/NBodyWnd.i"
	@echo "... 3D/src/NBodyWnd.s"
	@echo "... 3D/src/Octree.o"
	@echo "... 3D/src/Octree.i"
	@echo "... 3D/src/Octree.s"
	@echo "... 3D/src/Particule3D.o"
	@echo "... 3D/src/Particule3D.i"
	@echo "... 3D/src/Particule3D.s"
	@echo "... 3D/src/SDLWnd.o"
	@echo "... 3D/src/SDLWnd.i"
	@echo "... 3D/src/SDLWnd.s"
	@echo "... 3D/src/main.o"
	@echo "... 3D/src/main.i"
	@echo "... 3D/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

